import { Config } from '@ton/blueprint';

export const config: Config = {
    contracts: 'contracts',
    // Prebuilt Tact output already lives in build/ (generated by `npm run build`
    // in this directory) — Blueprint tests import compiled wrapper classes
    // directly from there rather than the tact.config.json plugin path, to
    // avoid coupling this cross-verification test to Blueprint's own Tact
    // wiring (see tests/README.md).
};
